# -*- coding: utf-8 -*-
"""QBIO_401_Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gjM-bXgMtxOjmA9JA2GrdZIe_sGHYYR
"""

read1 = open('/content/XI1_ATCACG_L001_R1_001.fastq')
read2 = open('/content/XI1_ATCACG_L001_R2_001.fastq')

def quality(file, readlen, threshold):
  qualities = [0] * readlen
  count = 0
  for i, l in enumerate(file):
    count+=1
    if i % 4 != 3:
      continue
    for j, q in enumerate(l):
      if ord(q) - 33 >= threshold:
        qualities[j] += 1
  qualities = [4*q/count for q in qualities]
  return qualities

r1_values = quality(read1, 250, 30)

r2_values = quality(read2, 250, 30)

print(r2_values)

read1.close()
read2.close()

read1 = open('/content/XI1_ATCACG_L001_R1_001.fastq')
read2 = open('/content/XI1_ATCACG_L001_R2_001.fastq')

def k_bases(file, readlen, threshold):
  k_values = [0] * (readlen+1)

  for i, l in enumerate(file):
    if i % 4 != 3:
      continue
    k_count = 0
    for j, q in enumerate(l):
      if ord(q) - 33 >= threshold:
        k_count += 1
    k_values[k_count] += 1

  k_values = [k for k in k_values]
  return k_values

k1 = k_bases(read1, 250, 30)

k2 = k_bases(read2, 250, 30)

read1.close()
read2.close()

import matplotlib.pyplot as plt
plt.plot(r1_values, label='r1', color = 'green')
plt.plot(r2_values, label='r2', color = 'blue')
plt.xlabel('Position Number')
plt.ylabel('Fraction of quality reads')
plt.title('Plot of k1 and k2')
plt.legend()
plt.show()

plt.plot(k1, label='k1', color = 'green')
plt.plot(k2, label='k2', color = 'blue')
plt.xlabel('k counts')
plt.ylabel('Number of Readings with k Quality Bases')
plt.title('Plot of k1 and k2')
plt.legend()
plt.show()

"""Question 3.a:
Sequences do seem to depend on read position. These positions are overall similar across readings, but we see dips at similar points for both. Specifically at the end of both readings the quality dips tremendously.

Question 3.b:
The first reading seems to be a decent bit better at the higher ranges. We see from k counts of 225 on, reading 1 has at least 2x the quality number of k quality bases.

Question 3.c: Yes, as sequences get longer errors and the process are more likely to occur. These eventual errors make it more difficult to get longer chains, and since read 2 follows read 1, this effect is compounded, making read 2 lower quality towards the end.
"""